// Builds a clean markdown report from a completed analysis for the Copy button.

export function buildMarkdownReport(analysis, { caseText, caseType, contextFlags, attachments }) {
  const {
    risk_score: risk = {},
    signals = [],
    classification = {},
    loss_estimate: loss = {},
    fact_assessment: facts = {},
    root_cause_analysis: rca = {},
    recommendation: rec = {},
  } = analysis || {};

  const lines = [];
  const push = (s = '') => lines.push(s);

  push('# FraudSense Investigation Report');
  push('');
  push(`**Generated:** ${new Date().toLocaleString()}`);
  push(`**Case type:** ${caseType}`);
  if (contextFlags && contextFlags.length) {
    push(`**Analyst context:** ${contextFlags.join(', ')}`);
  }
  if (attachments && attachments.length) {
    push(`**Attachments:** ${attachments.map((a) => `${a.name} (${a.kind})`).join(', ')}`);
  }
  push('');
  push('## Case Description');
  push('');
  push('> ' + (caseText || '').trim().replace(/\n/g, '\n> '));
  push('');

  // Risk score
  if (risk.score != null || risk.severity) {
    push('## Risk Score');
    push('');
    push(`**${risk.score ?? '—'}/100 — ${risk.severity ?? '—'}**`);
    if (Array.isArray(risk.factors) && risk.factors.length) {
      push('');
      risk.factors.forEach((f) => push(`- ${f.name}: ${f.weight}`));
    }
    push('');
  }

  push(`## Fraud Signals Detected (${signals.length})`);
  push('');
  signals.forEach((s) => {
    const basis = s.basis ? ` · ${s.basis}` : '';
    push(`- **${s.name}** — \`${s.strength}\` · _${s.category}_${basis}`);
    push(`  - ${s.reason}`);
  });
  push('');

  push('## Case Classification');
  push('');
  push(`- **Primary type:** ${classification.primary_type ?? '—'}`);
  if (classification.secondary_type) {
    push(`- **Secondary type:** ${classification.secondary_type}`);
  }
  push(`- **Confidence:** ${classification.confidence ?? '—'}`);
  push('');
  push(classification.reasoning ?? '');
  push('');

  // Loss estimate
  if (loss.confirmed || loss.likely_low || loss.likely_high) {
    push('## Loss Estimate');
    push('');
    push(`- **Confirmed:** ${loss.confirmed ?? '—'}`);
    push(`- **Likely exposure:** ${[loss.likely_low, loss.likely_high].filter(Boolean).join(' – ') || '—'}`);
    if (loss.basis) push(`- **Basis:** ${loss.basis}`);
    push('');
  }

  // Evidence basis
  const factGroups = [
    ['Observed Facts', facts.observed_facts],
    ['Analyst Assessments', facts.assessments],
    ['Unverified Hypotheses', facts.hypotheses],
  ];
  if (factGroups.some(([, items]) => Array.isArray(items) && items.length)) {
    push('## Evidence Basis');
    push('');
    factGroups.forEach(([label, items]) => {
      push(`**${label}**`);
      push('');
      (Array.isArray(items) ? items : []).forEach((it) => push(`- ${it}`));
      push('');
    });
  }

  push('## Root Cause Analysis');
  push('');
  push(`**Attack narrative**\n\n${rca.attack_narrative ?? '—'}`);
  push('');
  push(`**Entry point**\n\n${rca.entry_point ?? '—'}`);
  push('');
  push(`**Blast radius**\n\n${rca.blast_radius ?? '—'}`);
  push('');
  push(`**Watch for**\n\n${rca.watch_for ?? '—'}`);
  push('');

  push('## Recommended Action');
  push('');
  push(`### ${(rec.action ?? '—').toUpperCase()}  (confidence: ${rec.confidence ?? '—'})`);
  push('');
  push(rec.reasoning ?? '');
  push('');
  if (Array.isArray(rec.decision_logic) && rec.decision_logic.length) {
    push('**Decision logic**');
    push('');
    rec.decision_logic.forEach((step) => push(`- ${step}`));
    push('');
  }
  push('**Next steps**');
  push('');
  (rec.next_steps ?? []).forEach((step, i) => push(`${i + 1}. ${step}`));
  push('');
  push(`**Escalation path:** ${rec.escalation_path ?? '—'}`);
  push('');
  push('---');
  push('_Generated by FraudSense — REDWING AI Fraud Detection Platform_');

  return lines.join('\n');
}
